CREATE TABLE customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_first_name VARCHAR(50),
    customer_last_name VARCHAR(100),
    customer_phone_no VARCHAR(20),
    customer_email_address VARCHAR(100)
);

INSERT INTO customer(customer_first_name, customer_last_name, customer_phone_no, customer_email_address) VALUES('Adam', 'Smith', '+44678234112', 'adam.smith@mail.com');
INSERT INTO customer(customer_first_name, customer_last_name, customer_phone_no, customer_email_address) VALUES('Chris', 'Johnson', '+32628117812', 'chris.johnson@mail.com');
INSERT INTO customer(customer_first_name, customer_last_name, customer_phone_no, customer_email_address) VALUES('Jane', 'O''Dell', '+43275234192', 'jane.odell@mail.com');
INSERT INTO customer(customer_first_name, customer_last_name, customer_phone_no, customer_email_address) VALUES('Sam', 'Pattry', '+32111234111', 'sampattry@mail.com');