CREATE TABLE issue (
    issue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customer(customer_id) NOT NULL,
    issue_date TIMESTAMP NOT NULL,
    issue_description VARCHAR(250) NOT NULL,
    issue_solution VARCHAR(250),
    issue_status VARCHAR(20) NOT NULL,
    issue_edit_date TIMESTAMP
);

INSERT INTO issue(customer_id, issue_date, issue_description, issue_solution, issue_status, issue_edit_date) VALUES(1, NOW() - INTERVAL '3 days', 'Lorem ipsum dolor sit amet.', NULL, 'OPENED', NOW() - INTERVAL '1 days');
INSERT INTO issue(customer_id, issue_date, issue_description, issue_solution, issue_status, issue_edit_date) VALUES(1, NOW() - INTERVAL '5 days', 'Lorem ipsum dolor sit amet.', NULL, 'PROCESSING', NOW() - INTERVAL '3 days');
INSERT INTO issue(customer_id, issue_date, issue_description, issue_solution, issue_status, issue_edit_date) VALUES(3, NOW() - INTERVAL '10 days', 'Lorem ipsum dolor sit amet.', 'Pellentesque interdum est in fermentum scelerisque', 'RESOLVED', NOW() - INTERVAL '7 days');
INSERT INTO issue(customer_id, issue_date, issue_description, issue_solution, issue_status, issue_edit_date) VALUES(4, NOW() - INTERVAL '15 days', 'Lorem ipsum dolor sit amet.', 'Pellentesque interdum est in fermentum scelerisque', 'CLOSED', NOW() - INTERVAL '10 days');
